### ISSUE TITLE
account for the interrupted pulls

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenconf#22]
once we provide the "do not untar" option here, we could account for the interrupted `refgenie pull`s because now these just result in an incomplete archive. This could be confusing then.

**Comment by vreuter** [comment]
@nsheff do you know if we do anything like this for interrupted/incomplete SRA downloads in `geofetch`, and similarly for BAM conversions in `sra_convert`? If not, it seems like the logical framework for solving this issue here could be generalized for those other applications.

**Comment by nsheff** [comment]
geofetch is built on `prefetch` from `sratools`, which handles this there.

for bam conversions, `pypiper` handles this. So, we could use pypiper functionality to do this...

**Comment by michalstolarczyk** [comment]
I originally thought about leveraging `signal`/`atexit` to perform a checksum check and remove the archive if not passed.

**Comment by nsheff** [comment]
> I originally thought about leveraging `signal`/`atexit` to perform a checksum check and remove the archive if not passed.

I don't follow. why not just check after the pull? why rely on `atexit`?

**Comment by michalstolarczyk** [comment]
We won't  be able to check after the pull as we want to prevent the pull _interruption_, like `SIGINT`. So we will need to catch it and then react (with the invalid archive removal, for example). 
Or am I missing something?

**Comment by nsheff** [comment]
if the pull was interrupted, then we should assume the thing failed. no need to run a checksum on `atexit`!

just run the checksum after pulling. if it matches, solidify the pull... write to the config file, untar the archive, mark as complete, whatever, and you're done.

if something fails, you will never have written the config file, the archive will be incomplete, whatever. how does a checksum atexit help?

**Comment by michalstolarczyk** [comment]
ok. First of all, **I've missed this**: "The functions registered via this module (`atexit`) are not called when the program is killed by a signal not handled by Python", which means that `atexit` _wouldn't_ help to catch the interruption. 

>just run the checksum after pulling. if it matches, solidify the pull... write to the config file, untar the archive, mark as complete, whatever, and you're done.
>if something fails, you will never have written the config file, the archive will be incomplete,

yeah, that's exactly how it is designed right now, I think. My idea with this issue was to avoid having incomplete archive at the end.

**Comment by nsheff** [comment]
oh now I get it. what you really want to do is *remove the archive* in case of interrupt, without needing to check the checksum. So, the other part is correct. you can use the signal handler function to remove the archive in case of interrupt, that does make sense.
