### ISSUE TITLE
adding genome attributes to config file

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#25]
related to #7 (but for genomes instead of for assets)

what if we want to add some other attributes about a genome? examples include a description, URL to where it came from, what species it comes from, how long it is, etc.

maybe the config format should introduce an "assets" attribute under genome so they are not right under it?

**Comment by michalstolarczyk** [comment]
I've transferred it here since majority (if not all) of the related changes will be needed here

the question is: do we introduce this before we release `refgenie` as a whole?

**Comment by nsheff** [comment]
after is fine.

**Comment by nsheff** [comment]
This has come again, eg, https://github.com/databio/refgenconf/pull/46#discussion_r301821235

This is becoming higher priority. I think it will be critical to include a description of each genome on the server.

What would it take to solve this now?

- change the config format to introduce an assets attribute, so we can have other attributes right under the genome key
- add a new top-level attribute called 'config_version' to the genome config file. we'll be introducing version 0.2.
- make a new refgenie release that, if given a previous version (ie there's no 'config_version' specified), will say 'please update your config file'
- add a new refgenie command, `updatecfg`, that will take in a versionless cfg file and make it compliant with version 0.2
- then we just have to make the actual changes to the refgenconf functions to use the new version.

@vreuter, @michalstolarczyk do you think this is something we could accomplish by today or tomorrow if we focus?

I'm just thinking this is actually a rather major change, so it would be better to do it *before* we release refgenie into the wild rather than after (countering my opinion from last month I know).

**Comment by nsheff** [comment]
the other nice thing about this is that it will make the genome attributes infinitely flexible.

an alternative would be go have a 'genomes' section and an 'assets' section... the assets would then tie to genomes.

```
genomes:
  hg38:
    description: Genome derived from blah blah blah
    attr1: val1
    checksum: checksum from refget

assets:
   hg38:
     bowtie2_index:
      attr1: val1
      path: path/to/asset
````

Here the `assets` section would be exactly what we now call the `genomes` section.

**Comment by michalstolarczyk** [comment]
The first organization has my vote. The intrinsic hierarchy in the YAML files takes care of what we'd try to accomplish with the second one. So it just adds complexity IMHO

**Comment by michalstolarczyk** [comment]
_I think_ I'm pretty much done with the config file format changes

We need to adjust the tests, though.. 
@vreuter, this is clearly your area of expertise, could you take a look at it? I'd spend ages to understand and correct them

Because of that I could just test the changes using the CLI and working with `RefGenConf` in an interactive python session, but it seems to work as expected

**Comment by nsheff** [comment]
understanding those tests can be challenging. If @vreuter isn't around to make these changes, I'd say just comment out the failing tests for now... we need to move on.

**Comment by vreuter** [comment]
For future reference, tagging with `@pytest.mark.xfail` is probably easier
