### ISSUE TITLE
ValueError: To create config object, string should be config filepath; got 'genome_config.yaml'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#27]
weird error message:

```
>>> rgc = refgenconf.RefGenConf("genome_config.yaml")
Can't load config file 'genome_config.yaml'
FileNotFoundError[Errno 2] No such file or directory: 'genome_config.yaml'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheffien/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 51, in __init__
    "be config filepath; got '{}'".format(entries))
ValueError: To create config object, string should be config filepath; got 'genome_config.yaml'
```
I *did* provide a filepath. it just didn't exist...

**Comment by nsheff** [comment]
I think just:
- if the file doesn't exist, "that file doesn't exist", or "couldn't find file {file}" or something.

if the thing given really isn't a filepath, then the current message is fine.

**Comment by nsheff** [comment]
I see now the FileNotFoundError up there... that seems like the error that should be shown, not "string should be a config filepath"

**Comment by vreuter** [comment]
The message is meant to assist a user that calls the RGC constructor passing a variable as an argument rather than a literal value. Since that user wouldn't know the variable's value, he/she may not be expecting that it's a string and instead be expecting to pass a mapping of data. Perhaps the lack of clarity isn't worth the independence of assumption, though.

**Comment by nsheff** [comment]
I get what you're saying. but it confused me, I just didn't understand the message from the route that I took to get to it. I don't have a strong opinion here, you can do whatever you think is best.

**Comment by vreuter** [comment]
This will more directly point to the error: https://github.com/databio/refgenconf/commit/ae9d53806875f0c901cf403586f1ca54bc834e7f
