### ISSUE TITLE
refgenie clobbers existing assets

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#36]
if I try to download an asset that exists, refgenie just re-downloads it. Shouldn't it *not* re-do an existing asset unless prompted to overwrite?

**Comment by vreuter** [comment]
Tested in https://github.com/databio/refgenconf/commit/6bdc534348859fea62fd108566c601a67208549f and https://github.com/databio/refgenconf/commit/7031b0fa40a20c9a8330b2199bb6f109c328a01b
