### ISSUE TITLE
why would get_asset return a relative to pwd path?

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#44]
I'm confused by something...refgenie seek gives me the path correctly:

```
refgenie seek -c genome_config.yaml  -a salmon_index -g mouse_chrM2x
refgenie 0.4.5-dev
/home/nsheff/mouse_chrM2x/salmon_index
```

but if I add a file with the same name as the asset path in the `pwd`:

```
touch salmon_index
```
Then now, `get_asset` returns that relative to the `pwd`:

```
refgenie seek -c genome_config.yaml  -a salmon_index -g mouse_chrM2x
refgenie 0.4.5-dev
salmon_index
```

I cannot figure out why it works this way. Is this a bug or a feature?

In any case, I want to eliminate this behaviour... I would thinkthe local folder where I'm running the command should definitely *not* affect what is returned by `get_asset` or `refgenie seek` ...

**Comment by nsheff** [comment]
I would guess this is coming from here: 

https://github.com/databio/refgenconf/blob/5db4ce611ebbca1231cfd00e1a342048423f8f05/refgenconf/refgenconf.py#L176-L177

**Comment by vreuter** [comment]
what's `genome_config.yaml`?

**Comment by nsheff** [comment]
basically, http://refgenie.databio.org/en/latest/genome_config/

the `path` is relative to the genome config file if it's relative...
