### ISSUE TITLE
add setdefault method

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenconf#50]
we need a setdefault method to change default tag of the asset

it should prompt on override: you currently have "...."

**Comment by michalstolarczyk** [comment]
if we change tag `X` to `default` do we remove `X` from the config?

**Comment by nsheff** [comment]
Hmm, good question.

also do we need a way to move a default into a tagged slot?

if we forced all assets to have tags, then default could just be a pointer to an existing tag. That would answer this question, but would require all assets to have a tag.
