### ISSUE TITLE
add tag layer to the config format

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenconf#51]
with  [`refgenie v0.6.1`](https://github.com/databio/refgenie/pull/88) we start tagging assets, so config file now needs a new layer for tags
it's an update to the config version number (`0.3`).

**Comment by nsheff** [comment]
`update_assets(` will need a signature change to accommodate:

```
            rgc.update_assets(genome, asset, tag, {
                CFG_ASSET_PATH_KEY: build_pkg[ASSETS][asset][PTH].format(**asset_vars),
                CFG_ASSET_DESC_KEY: build_pkg[ASSETS][asset][ASSET_DESC]
            })```
```

The new arg is 'tag'. If `tag` is none, it can be set to `default`.

**Comment by nsheff** [comment]
`get_asset` will need a new optional arg, `tag`, which if set to None, returns the default asset.

**Comment by michalstolarczyk** [comment]
https://github.com/databio/refgenconf/commit/cad79708f9fd5fd0a732928c31d8fa472292f3b2
