### ISSUE TITLE
default seek keys

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#60]
Right now seeking for the `fasta` asset doesn't work, because it expects you to type `fasta.fasta`:

```
 refgenie seek hg38/fasta
/ext/yeti/refgenomes/hg38/fasta/default
nsheff@puma:/project/shefflab/www/refgenie_raw$ refgenie seek hg38/fasta.fasta
/ext/yeti/refgenomes/hg38/fasta/default/hg38.fa
```

See, the vanilla `fasta` key  is just pointing to the folder.

Do we want to enable a default when there are keys present? I thought if the name of the seek key matched the asset name, then the repetition shouldn't be required?

**Comment by nsheff** [comment]
Related issue: 

```
refgenie getseq -g hg38 -l chr1:5-10
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.5/site-packages/pyfaidx/__init__.py", line 359, in __init__
    if mutable else 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/ext/yeti/refgenomes/hg38/fasta/default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 659, in main
    refgenie_getseq(rgc, args.genome, args.locus)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 506, in refgenie_getseq
    fa = pyfaidx.Fasta(rgc.get_asset(genome, "fasta"))
  File "/home/nsheff/.local/lib/python3.5/site-packages/pyfaidx/__init__.py", line 996, in __init__
    build_index=build_index)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pyfaidx/__init__.py", line 368, in __init__
    "Cannot read FASTA file %s" % filename)
pyfaidx.FastaNotFoundError: Cannot read FASTA file /ext/yeti/refgenomes/hg38/fasta/default
```

**Comment by nsheff** [comment]
getseq appears to be seeking for `fasta` instead of `fasta.fasta`.

I think we should make `fasta` work as it used to

**Comment by michalstolarczyk** [comment]
We might do that.

It is the question of what's the behavior a user expects. I've explicitly implemented it this way: 

https://github.com/databio/refgenconf/blob/b9f67339aee733eed853dd537a0149eb715d8ed6/refgenconf/refgenconf.py#L851-L855

my reasoning was: if my asset is a dir (we decided to point to it with `.`) I can refer to it with no `seek_key`, otherwise (if it is a set of files where each of them has a separate seek_key defined) I have to specify the one I'm referring to explicitly

**Comment by nsheff** [comment]
I don't see a disadvantage of:

if the asset has seek keys, and a seek key is defined with the same name as the asset, then that is the default seek key returned if no key is provided.

you could still accomplish what you are proposing by putting in a self-named seek key with pointer to the folder.

but with your method you cannot do what we want to do in most cases, which is point to a file without a seek key, even when seek keys are defined (like in the case of `fasta`, a good example)
