### ISSUE TITLE
Extras for especially common assets

### ISSUE THREAD

**Issue by vreuter** [databio/refgenconf#8]
Something as ubiquitous and potentially error-fraught as aligner indices _could_ have some tool-specific validation code. https://github.com/databio/pepatac/blob/master/pipelines/pepatac.py#L346-L362

Counterpoints:
- This opens the door to the need to update according to version changes in the underlying tools for which such extras were provided
- A sort of tacit endorsement of particular tools

**Comment by nsheff** [comment]
I don't quite understand exactly the question, but I think this is an interesting idea...

but I think the general refgenconf should simply give back the *top-level item*, whatever it is (most likely a folder), for the asset of interest. Then the user can do whatever they want with it (validate, etc).

I'd be wary of adding any tool-specific *anything* into this object itself.

**Comment by nsheff** [comment]
but where such things *could* go would be as an element in the genome configuration file...
