### ISSUE TITLE
get_asset terminology

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#82]
is there a reason we use `get_asset` instead of `seek_asset`?

the 'get' terminology is really confusing because it seems like it should be a synonym of `pull`, not of `seek`...

**Comment by stolarczyk** [comment]
there's no reason at all..

**Comment by stolarczyk** [comment]
this issue is similar to #84. We need to rename (or add if missing) `RefGenConf` methods so that they perform identical functions as the CLI commands, but output python objects
