### ISSUE TITLE
list_local is returning strings

### ISSUE THREAD

**Issue by nsheff** [databio/refgenconf#84]
```
rgc.list_local()
('hs38d1, rCRSd', '              hs38d1/   fasta.chrom_sizes:default, fasta.fai:default, fasta:default\n               rCRSd/   fasta.chrom_sizes:default, fasta.fai:default, fasta:default')
```

Shouldn't this return actual python lists so that these can be used as units?

**Comment by stolarczyk** [comment]
`list_assets_by_genome`  is probably what you are after.

try:

```python
rgc.list_assets_by_genome(include_tags=True)
```

this returns a nicely structured `OrderedDict` that you can key by genome

**Comment by stolarczyk** [comment]
having said that, we should rename `list_local` since it seems to be confusing
