### ISSUE TITLE
mimic CLI terminology in RefGenConf object's methods

### ISSUE THREAD

**Issue by stolarczyk** [databio/refgenconf#86]
this issue is similar to #84. We need to rename (or add if missing) `RefGenConf` methods so that they perform identical functions as the CLI commands, but output python objects

_Originally posted by @stolarczyk in https://github.com/databio/refgenconf/issues/82#issuecomment-595758456_

**Comment by nsheff** [comment]
In my latest test on dev this was much more intuitive with these changes!
